//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Praktika_9.ApplicationData
{
    using System;
    using System.Collections.Generic;
    
    public partial class Zapisi
    {
        public int id { get; set; }
        public string Familia { get; set; }
        public string Name { get; set; }
        public string Otchestvo { get; set; }
        public string SvobodnoeOkno { get; set; }
        public System.DateTime DateTime { get; set; }
        public int DateID { get; set; }
        public int StatusID { get; set; }
        public int ClientID { get; set; }
    
        public virtual Client Client { get; set; }
        public virtual Date Date { get; set; }
        public virtual Status Status { get; set; }
    }
}
